on:
  release:
    types: [published]

name: Publish

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo login ${{secrets.CARGO_TOKEN}}
      - run: cargo publish
